### ISSUE TITLE
Meetup checklist

### ISSUE THREAD

**Issue by maurolepore** [ixpanteria/meta#2]
# ixpanteria-checklist

https://bit.ly/ixpanteria-checklist

## Antes

- [ ] Anunciar en el canal mas apropiado, e.g. #ixpanteria
- [ ] Crear/actualizar la invitacion del calendario.

## Durante

- [ ] Abrir la reunion.
- [ ] Nominar co-host/moderador/time-keeper.
- [ ] Compartir pantalla.
- [ ] Grabar.
- [ ] Preguntas, comentarios, discusion.
- [ ] Fin 

## Despues

- [ ] Subir el video publicamente, e.g. en YouTube.
  - Titulo del capitulo como aparece en el repositorio.
  - Descripcion del capitulo como aparece en el repositorio.
- [ ] Agregarlo al playlist general, donde estan todos los videos.
- [ ] Agregarlo al playlist de la serie, usando el nombre del repositorio.
- [ ] Anunciar en medios, e.g. en LinkedIn, incluyendo:
  - Titulo del capitulo como aparece en el repositorio.
  - Descripcion del capitulo como aparece en el repositorio.
  - Link al repo.
  - Link al video.
  - Link al playlist.
  - Link al website del proyecto, e.g. el home de una organizacion de GitHub dedicada.
